### ISSUE TITLE
Create a calculator

### ISSUE THREAD

**Issue by sundaramvivek10** [votca/xtp#495]
A calculator that can read the topology file and do the Ewald's summation for the set of molecules

**Comment by felipeZ** [comment]
## Task
We will need to work on the following tasks:
### TODO
* [ ] Create a new job in `xtp_run` called **ewald**
* [ ] Get the topology object
* [ ] Convert the MD molecule into an electrostatic molecule (from segments to static segments)
* [ ] Provide the XML map and the MPS files
* [ ] Call the static mapper
* [ ] Feed the previous information into the Ewald library

**Comment by JensWehner** [comment]
taken over by @rubengerritsen
